[package]
name = "nn"
version = "0.3.0"
authors = ["Pro465 <namitapro0987@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.9.2", optional = true }

[features]
default = ["rand"]
